version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/epochease
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app # Mount the server code directory for live reloading
      - /usr/src/app/node_modules
    command: npx nodemon app.js

volumes:
  mongo-data:
